[versions]
agp = "8.13.1"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
material = "1.10.0"
activity = "1.8.0"
constraintlayout = "2.1.4"
navigationFragment = "2.6.0"
navigationUi = "2.6.0"
annotation = "1.6.0"
lifecycleLivedataKtx = "2.6.1"
lifecycleViewmodelKtx = "2.6.1"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version = "1.3.0" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version = "3.7.0" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version = "1.7.1" }
material = { group = "com.google.android.material", name = "material", version = "1.13.0" }
activity = { group = "androidx.activity", name = "activity", version = "1.11.0" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version = "2.2.1" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version = "2.9.6" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version = "2.9.6" }
annotation = { group = "androidx.annotation", name = "annotation", version = "1.9.1" }
lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version = "2.9.4" }
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version = "2.9.4" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

